### ISSUE TITLE
kinaseSubstrateScore

### ISSUE THREAD

**Issue by joonan30** [PYangLab/PhosR#2]
Hi,

Thanks for the nice tool. I am trying to apply this to the human phospho dataset. Few questions,

1. Does this `kinaseSubstrateScore` function take human motif file? I passed the 'PhosphoSite.human` but the function takes mouse motifs only (the line 6 -> `PhosR::motif.mouse.list`)
2. I think it takes known PTM sites for kinase activities. I think it would be great if you implement PWM for kinase motif prediction? Or I might miss the function in this package ..
3. Does this dataset `phospho.L6.ratio.pe` include ratio ( experimental condition / background)? or some log intensity value? I am trying to dig out description from the paper but it's not clear..

Cheers,

**Comment by HaniJieunKim** [comment]
Hi @joonan30 

Many thanks for the interest in our package.

1. Does this kinaseSubstrateScore function take human motif file? I passed the 'PhosphoSite.humanbut the function takes mouse motifs only (the line 6 ->PhosR::motif.mouse.list`)

We have updated the kinaseSubstrate Score function so that the user can specify the species from either human, mouse, or rat. The specified species specific motif list will be used. Please see the update [here](https://github.com/PYangLab/PhosR/commit/af8c6a191a2fd723aad29eb8b95cd953533c457e). 

2. I think it takes known PTM sites for kinase activities. I think it would be great if you implement PWM for kinase motif prediction? Or I might miss the function in this package ..

We implement PWM in PhosR. Please [see function](https://github.com/PYangLab/PhosR/blob/master/R/getMotifFreq.R) `createFrequencyMat` and specifically lines 11-16 for example code. 

3. Does this dataset phospho.L6.ratio.pe include ratio ( experimental condition / background)? or some log intensity value? I am trying to dig out description from the paper but it's not clear..

Please refer to Step 6 of [our protocol](https://pyanglab.github.io/PhosR/articles/web/PhosR_STAR_protocols.html) for more details. The phospho.L6.ratio.pe is generated from SILAC data; therefore, the generated data is relative to the control. 

Many thanks,
Hani
