### ISSUE TITLE
Issues with kinaseSubstrateScore and substrateList functions

### ISSUE THREAD

**Issue by AimeeD90** [PYangLab/PhosR#5]
Hi there,
Nice work, but I think there might be two issues with kinaseSubstrateScore and substrateList functions. 

First in kinaseSubstrateScore function, it appears that motif.mouse.list is used as the only resource for motifs scoring regardless of the species to work with. Since species matters a lot in kinase analysis, hope you can fix that.

And another small issue that related with substrateList function. When substrate number is less than the preset threshold (inclusion), it crashes with an error like "Error in substrate.list[[i]] : subscript out of bounds". The problem is caused by "names(substrate.list) <- kinaseSel" , where substrate.list is a null variable. To avoid this, it would be better to move this code into the if block.

if (length(sel) >= inclusion) {
      count <- count + 1
      substrate.list[[count]] <- sel
      kinaseSel <- c(kinaseSel, colnames(phosScoringMatrices$combinedScoreMatrix)[i])
      names(substrate.list) <- kinaseSel
    }

Look forward to an update, Thanks!

**Comment by HaniJieunKim** [comment]
Hi @AimeeD90 

Many thanks for the interest in our package.

We have updated the kinaseSubstrate Score function so that the user can specify the species from either human, mouse, or rat. The specified species specific motif list will be used.  

Please see the update [here](https://github.com/PYangLab/PhosR/commit/af8c6a191a2fd723aad29eb8b95cd953533c457e). We have also removed the problematic line relating to kinaseSel. 

Many thanks,
Hani
