### ISSUE TITLE
Meaning of Mulitiplicity 

### ISSUE THREAD

**Issue by kej226** [PYangLab/PhosR#9]
Thank you for sharing code. 

I have some issues about understanding multiplicity meaning. 
As explained below, i can understand the meaning of multiplicity, but what values ​​should i consider when analyzing duplicated data? (Ex, Acaca-S79 multiplicity:1, Acaca-S79 multiplicity:2  Both have values. )

Multiplicity: number of phosphorylation sites co-localized within the same phosphopeptide.
  _1: phosphosite identified in a mono-phosphorylated peptide
  _2: phosphosite identified in a di-phosphorylated peptide
  _3: phosphosite identified in a tri-phosphorylated peptide

**Comment by HaniJieunKim** [comment]
Hi @kej226 

Many thanks for your interest in our package.

Please refer to our [protocol paper](https://www.sciencedirect.com/science/article/pii/S2666166721002926?via%3Dihub) and specifically section Troubleshooting Problem 5. We discuss how to go around the issue of multiplicity in the data.

Whilst we do not investigate the best way to deal with multiplicity of phosphosites in PhosR (it was beyond the scope of our paper), we provide potential solutions to go around having duplicate sites, as this causes error in some of our code.

- PhosR implements a versatile function, ‘phosCollapse’, that can be used to generate a combined score for the multiply quantified values. The ‘stat’ argument denotes how we will summarize each phosphosite quantifications across conditions so that for each value in the multiplicity we derive a single quantification, and the ‘by’ argument denotes the method by which to select among the multiplicity.
- Another simpler solution is to average the multiple sites for each sample.

Example code is provided in [the paper](https://www.sciencedirect.com/science/article/pii/S2666166721002926?via%3Dihub).
